### ISSUE TITLE
Add on doesn't work for new version of Anki

### ISSUE THREAD

**Issue by whereingroovy** [is343/anki_delay_deck#11]
I have Anki version 2.1.66, and I got an error with the add on - it no longer works.

**Comment by is343** [comment]
Hello, can you tell me what the error says?

**Comment by is343** [comment]
@whereingroovy can you try again? I just posted an update earlier, and I think the issue was that I had messed up the supported version ranges. So it was probably saying that your version is no longer supported.

I just updated the version number range for the addon to fix it.
If it's still not working, then try removing then reinstalling the addon (id: `43919973`)

**Comment by whereingroovy** [comment]
It works now, thank you so much!!!
