### ISSUE TITLE
Anki delay overdue cards

### ISSUE THREAD

**Issue by JanAnki** [is343/anki_delay_deck#8]
Hello, I wanted to delay cards for 2 days. But now I want to study again. The problem is that the cards are still delayed and i don´t know how to bring them back. I am really desperate, so i am thankful if anyone can help me. 

Also i tried to get the cards back with tiping in -10 days for example but still no card i shown.

**Comment by is343** [comment]
Hi, sorry to hear you're having trouble. 

Instead of doing -10 immediately, did you try -2 at first to undo it?

If you are really desperate, you have a few options. 
You can try the study ahead option in the deck custom study menu. 
You can try pulling your decks from ankiweb. 
Anki also saves an old version of the decks in the folder that they are saved in. You can change the filename to use that. 
You can try to just wait and see the cards that come up tomorrow.
